### ISSUE TITLE
Sort feature on main table view doesn't work for some integer properties

### ISSUE THREAD

**Issue by caseywreed** [caseywreed/NSS-PingPong-Frontend#9]
Some integer and number properties don't sort correctly in the main table view of the front page. For some reason, numbers like `Cohort` sort correctly, but `Win Percentage`, `Games`, etc.. don't sort by ascending / descending order.

Although I'm certainly still a beginner, I'm opening this up to the open-source beginner community. The help would be greatly appreciated!

**Comment by techtocore** [comment]
Hello @caseywreed  , i would like to help you with this.
